### ISSUE TITLE
__calback function wont respond but event on Oracle Contract Shows Data in Events

### ISSUE THREAD

**Issue by RaminSubZero** [cryptoland-blockchain-laboratory/Bridge-oracle-system#1]
Hi 
```
pragma solidity ^0.5.9;
import "./BridgePublicAPI.sol";
contract priceFeed is BridgePublicAPI {
    
    event price(uint256 _amount);
    
    string public BTCUSD;
    constructor() public {
        send_query();
    }
    function send_query() public {
        bridge_query("URL", "json(https://api.pro.coinbase.com/products/BTC-USD/ticker).price");
   }
    function __callback(bytes32 _myid, string memory _result) public {
        require(msg.sender == oracle_cbAddress());
        BTCUSD = _result;
        uint256 res =  parseInt(_result, 0);
        emit price(res);
    }
}
```
This is The Example In Documentation 
But Nothing Returns in My Smart Contract 

txid = d4f8669b69a9b4716611c5d41b33d00e8dbfb78a1112c13945ee34f4936e4754
fullnode = nile.testnet
contract address = TDzjMAsoaG7HcrjynjhE9Epta39Wp6JnKQ

**Comment by cryptoland-blockchain-laboratory** [comment]
Dear Ramin

All parts work well. We have implemented even both get and post methods.
However, as you well know we are on testnet right now and we are working to
improve servers to be able to have 99.99% up-time on mainnet. It is likely
that when you had tried to send request servers were down and we were
working on it. Try to use our oracle services but note that it is not
stable yet due to testing time by time by our developers team.
Let us publish our mainnet and we will provide fully stable platform for
you, dear users.

Kind regards
Hassan Golmohammadi
Head of Bridge Oracle
